### ISSUE TITLE
Function.prototype.toString error at render

### ISSUE THREAD

**Issue by tbrasington** [airbnb/react-sketchapp#217]
Hello

_I am Reporting a bug or issue_

**Expected behavior:**
render to Sketch

**Observed behavior:**

Error is thrown when running npm run render

```
TypeError: undefined is not an object (evaluating 'Function.prototype.toString')
```
In all examples, the error is happening on this line

```
var funcToString = Function.prototype.toString;
```

which is part of this function

```
function isNative(fn) {
  // Based on isNative() from Lodash
  var funcToString = Function.prototype.toString;
  var hasOwnProperty = Object.prototype.hasOwnProperty;
  var reIsNative = RegExp('^' + funcToString
  // Take an example native function source for comparison
  .call(hasOwnProperty
  // Strip regex characters so we can use it for regex
  ).replace(/[\\^$.*+?()[\]{}|]/g, '\\$&'
  // Remove hasOwnProperty from the template to make it generic
  ).replace(/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g, '$1.*?') + '$');
  try {
    var source = funcToString.call(fn);
    return reIsNative.test(source);
  } catch (err) {
    return false;
  }
}
```

**How to reproduce:**
Although I noticed the error on my personal project, it is also happening in the following example projects:

- Basic-setup
- Generative-colours
- styled-components
- profile-cards

**Sketch version:**
47 (45396)

**Node version**
tried on v8.7.0 and v9.3.0

---
I started getting this issue today, earlier in the week everything was running ok. I haven't made any knowing changes to my machine setup.

I was wondering if anyone else is having this issue or knows where to look further for debugging. Any help is greatly appreciated.

**Comment by jxjshaw** [comment]
experiencing this as well...downgrading sketch didn't help

**Comment by mathieudutour** [comment]
it's because of macOS 10.13. Update Sketch, it's fixed in version 47.1 if I remember

**Comment by tbrasington** [comment]
Hi @mathieudutour thank you for getting back to me. I can still reproduce on 47.1 (45422) but its good to know its OS level so I can work something else out 👍

**Comment by mattborn** [comment]
@tbrasington Were you able to work this out? Tried 47 and 47.1. Still getting the same error.

**Comment by tbrasington** [comment]
V1 of react-sketchapp was released this weekend which resolved it for me.

**Comment by gtaranti** [comment]
Same error with macOS 10.13.2 - Sketch 47.1 - react-sketchapp v1.0

**Comment by mathieudutour** [comment]
then it was probably fixed in 48
