### ISSUE TITLE
nmp run render not draw in sketch

### ISSUE THREAD

**Issue by andex** [airbnb/react-sketchapp#26]
I am beginner and i have a problem :)

I do all by instruction and then run example projects it open sketch, but nothing to draw.

Can anyone help me?

Sketch 43.2
npm -v 3.10.10
node v6.9.5

**Comment by raulalgo** [comment]
I'm having the same issue

Sketch 43.2
npm 4.1.2
node 7.7.1

**Comment by zaqqaz** [comment]
Seems like you just forgot this step **Open a new Sketch file**

**Comment by andex** [comment]
OMG, its working :)
I did close all tabs in Sketch, and restart it, and it's working. Thanks!

**Comment by raulalgo** [comment]
Not for me. The new file is open and just in case I tried to restart Sketch, but still nothing. I've managed to link it as a plugin though, but not through npm run render

**Comment by zaqqaz** [comment]
@raulalgo can you provide console output ?

**Comment by ChristophLabacher** [comment]
Same here: Document gets focused, nothing happens. Plugin works fine!

![bildschirmfoto 2017-04-26 um 12 06 31](https://cloud.githubusercontent.com/assets/7572627/25429303/cface454-2a78-11e7-8cc2-e53d1e81e1d5.png)

**Comment by raulalgo** [comment]
`> basic-setup@1.0.0 render /Users/ralvarezgo/Documents/personal/2017 04 26 react-sketch/react-sketchapp/examples/basic-setup
> skpm build --watch --run

🖨  Copied src/manifest.json in 8ms
Executing post-build scripts
⛏  Built ./my-command.js in 1722ms
(null)`

Same as @ChristophLabacher. The window gets focused but nothing happens.

**Comment by ChristophLabacher** [comment]
I think I found something. Is it possible that a space character in one of the parent folder names of the project causes it to fail? Copied everything to a different path and now it works!

**Comment by raulalgo** [comment]
Exactly! Now it works!

Thanks everyone!

**Comment by mathieudutour** [comment]
> Is it possible that a space character in one of the parent folder names of the project causes it to fail?

Yes it did. I fixed it in `skpm@0.9.3` (just released)

**Comment by jongold** [comment]
Looks like everyone got it sorted, sorry for the hiccups. We should figure a way of opening Sketch to a blank document if it's not open yet.

**Comment by mikeyavorsky** [comment]
@mathieudutour I still get the same behavior, with `skpm@0.9.3` installed and a new Sketch file open, when there is a space character in a parent folder name. Focus goes to the Sketch window, but nothing is drawn.

```
➔ npm run render

> colors@ render /Users/Mike/Dropbox/Documents/Work/2017/2017-04/20170427-Yavorsky-Try-React Experiments/react-sketchapp/examples/colors
> skpm build --watch --run

🖨  Copied src/manifest.json in 16ms
Executing post-build scripts
⚒  Built main.js in 4160ms
(null)
```

**Comment by daouchovny** [comment]
Mine is showing as follows, anyone knows why :O?

<img width="503" alt="error screenshot" src="https://cloud.githubusercontent.com/assets/13806904/26397752/363569e4-402c-11e7-9c33-eab17c3f37b0.png">

**Comment by jongold** [comment]
Hey! What folder are you running it from? The main directory or one of the
examples folders?

**Comment by daouchovny** [comment]
@jongold The react-skethapp folder is under my username directory. I try again, and the error becomes below: Still try to figure out :'(
<img width="653" alt="screen shot 2017-05-24 at 10 06 34 am" src="https://cloud.githubusercontent.com/assets/13806904/26415850/bc68b57a-4068-11e7-9b4d-a2fbae6c2c5b.png">

**Comment by jongold** [comment]
@daouchovny this is a bug with Sketch 44 that we're working on fixing :( https://github.com/airbnb/react-sketchapp/issues/72

**Comment by daouchovny** [comment]
@jongold Awesome! Thank you so much! (Yes my Sketch version is 44.1.)
